INSERT INTO scenes(scenes, choiceA, choiceB, createdAt, updatedAt) VALUES 
('As you finish your daily training you head to the market in your city to gather groceries to make yourself a meal. Everything is good and is normal as usual except one thing. There seems to be a gloomy presence over everyone, and no one really seems to care what goes around them. The people on 
the market stores seem to be in a sort of trance. You finish your shopping and think nothing of it, as you reach the end of the market , in the corner of your eye you catch a glimpse of what seems to be a shadowy figure that quickly tries to hide in the alley to the right of you.', 'Will you act and figure out what the figure was? Do the people of the market bother you?',
'Will you choose to ignore and go about your day because of your hunger?',
CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('You chose to investigate and find out thatthe shadow was a soldier of the demon. You choose to fight him and defeat him. Thesoldier in the floor weak and on the brink of death notices the crest hanging at your neck. A crest that was given to you by your father. With his last breath curses it. Once he is no longer alive, the people of the market seem to come back to their normal selves and have no recollection of what happens. You go home curious and ask your father about the crest in which in return tells you the story of the war.',
'Will you choose to go in an adventure to free the people of Shadowfall and save the goddess? It will put you in a dangerous situation and possibly will haveto battle monsters to get to your goal.',
'Will you choose to help but stay inside the kingdom and try to gather folk to help you.',
CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('With the new acquired knowledge, youdecide to bring peace to both kingdoms, and set out on an adventure, an Epic Adventure. The first thing you know you will need is to find the spider who has the power to put everyone to sleep. With the destruction of the spider, you will be able awaken the goddess and finally be able to close the gate to the netherworld. You start your route towards Shadowfall. Starting on a path at the edge of Clareville you head to wards shadowfall. It appears to always be night there, because of the darkness. You decide to head towards the castle where the old king of shadow fall once lived. As you get closer you notice a path that splits in two. No signs tells you 
which way is the correct way. Only thing that makes the paths different is on the path on the left. There seems to be some type of  black power on the floor.',
'Will you choose to follow the path with the black powder.',
'Will you choose to play it safe and go towards the route that doesn’t have anything on it?',
CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Taking this path puts you on track to the castle. In the middle of the path you notice 2 goblins in sleeping in the path.',
'Decide to sneak past the sleeping goblins trying not to wake them up.',
'Decide to try to take a different route and not risk waking up the goblins.',
CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sneaking past the goblins was a hard thing to do without waking them up. However, what you didn’t know was that the goblins were the only thing that would Alert other monsters. You are safe. As you make your way in the castle, you notice that it is empty. When you make your way to the throne room you notice that its covered in web. A clue to yourself. This means the spider is in the throne room. Navigating and trying to find the spider you notice a small but shiny object on the throne itself. As you get closer, you seem to get sleepier and sleepier.',
'You decide to stay and figure out a way to stay awake.',
'You try to push through the sleepiness, I can handle it you say.',
CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO scenes(scenes, createdAt, updatedAt) VALUES 
('the shadow figure you ignored was a soldier of the demon. With the power given to him, he was able to turn the people of Clareville to monsters and overthrow the kingdom.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('The thought of being in danger makes you feel uneasy. You decide to try to fortify your kingdom, but no one pays much mind to you. Eventually, the forces of darkness are strengthened, and the kingdom is attacked. All fall, no one survives.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('You follow the path on the right and continue your journey. As you make you way towards the path a thick fog covers you and you are not able to see much in front of you.  Every step forward makes it harder to see, you get nervous and start walking faster. You slip and fall down a decent that runs off a cliff. You fall to your death.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Trying to avoid the goblins you try to make you way throw the thick forest that surround the path. Everything goes well until you step on a branch that breaks and makes a loud snapping sound. The goblins are now awake and start chasing you along with monsters in the forest. You try to fight you way outbut are outnumbered. The townsfolk never hear from you again.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('You fall asleep. The only chance of reviving the deity was onyour hands. There is no more you can do. The spider comes towards you and bites you, putting you in an eternal sleep. The goblins find you eventually and drive your sword through your heart.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('You push through the sleepiness by taking your sword, placing It on your palm, and squeezing it until bleeding. The pain of the cut allows you to fully awake and realize that the spider is on the throne is what makes you sleepy. With your sword you strike it killing it instantly. With this a wave of power is release, the deity is awoken. Your mission is over. She will handle the rest.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);